------------------------------------------------------------------------------
-- (c) Copyright 2019 Vyaire Medical, or one of its subsidiaries.
--     All Rights Reserved.
------------------------------------------------------------------------------
-- Tests fabian Terminal Interface library
------------------------------------------------------------------------------

ft      = require "fabian-Terminal"
pubFTI  = require "FTI-Public-Define"
verify  = require "verify"
utility = require "utility"

local portName = "COM6"
local on       = pubFTI.onOffState.ON
local off      = pubFTI.onOffState.OFF

print('fabian-regression-hfo-dual-limb-test: (' .. os.date() ..  ')')

local function testCPAP()
    print('Test pressure and backup pressure in CPAP mode:')
    print('------------- step 23 ---------------')
    ft.setVentMode(pubFTI.ventMode.CPAP)
    ft.setFlowMin__lpm(5)
    ft.setCPAP__mbar(5) 
    ft.setPManuel__mbar(15)
    ft.setBackup(0)
    print('------------- step 24 ---------------')
    print('INTERACTIVE: Decrease the low volume alarm threshold.')
	print('    - Press the alarm limits physical button.')
	print('    - On the alarm limits screen press the "MVexp" lower limit.')
	print('    - Spin the rotary knob to set the limit to "off". Press the nob to confirm the setting.')
	utility.promptForContinue()
    print('------------- step 25 ---------------')
    ft.delay_sec(30)
	print('------------- step 26 ---------------')
	verify.EXPECT_EQ_SET(ft.getWave(10).Pressure, 5, pubFTI.pressureTolerance__cmH2O) 
	verify.EXPECT_EQ(ft.getBTB().meanPressure, 5, pubFTI.pressureTolerance__cmH2O) 
	print('------------- step 27 ---------------')
	ft.setBackup(5)
    print('------------- step 28 ---------------')
    print('INTERACTIVE: Confirm backup is kicking in.')
	print('    - Confirm on the graph that 5 backup breaths are periodically occuring.')
	print('    - Confirm that the peak pressure shown on the graph during the breaths is approximately 15 mbar.')
	print('    - Confirm that the "Backup Active" alarm is shwon while tyhe backip nreaths are occuring.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
    print('------------- step 29 ---------------')
    print('INTERACTIVE: Simulate spontaneous breaths.')
	print('------------- step 30 ---------------')
    print('INTERACTIVE: Check that there is no backupup ventilation.')
	print('    - Confirm the 5 periodic backup breaths are no longer occurring and being drawn on the graph.')
	print('    - Instead you will see a pattern based on how you squeezed the test lung.')
	print('    - Confirm the back up alarm does not go off during this time.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 31 ---------------')
    print('INTERACTIVE: Stop simulating spontaneous breaths.')
	print('------------- step 32 ---------------')
    print('INTERACTIVE: Confirm backup is kicking in.')
	print('    - Confirm on the graph that 5 backup breaths are periodically occuring.')
	print('    - Confirm that the peak pressure shown on the graph during the breaths is approximately 15 mbar.')
	print('    - Confirm that the "Backup Active" alarm is shwon while tyhe backip nreaths are occuring.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print("CPAP test PASSED")
end


local function testCMV()
    print('Test pressure and graph in CMV mode:')
    print('------------- step 33 ---------------')
	ft.setVentMode(pubFTI.ventMode.IPPV)
    ft.setIFlow__lpm(8)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20)
	ft.setETime__sec(8) --e-time must be before freq, not sure why
	ft.setBPM__bpm(30)
	ft.setITime__sec(1)
	ft.setO2(21)
	print('------------- step 34 ---------------')
    ft.delay_sec(30)
	print('------------- step 35 ---------------')
	print('INTERACTIVE: Confirm that the graph shows a periodic breathing cycle.')
	print('INTERACTIVE: Confirm that the artifical lung is inflating and deflating.')
	verify.EXPECT_EQ(ft.getBTB().peakPressure, 20, pubFTI.pressureTolerance__cmH2O) 
	verify.EXPECT_EQ(ft.getBTB().PEEP, 5, pubFTI.pressureTolerance__cmH2O) 
	print('INTERACTIVE: No active alarms should occur during this time.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 36 ---------------')
	print('INTERACTIVE: Press the button to the left of the graph to view the Volume Graph.')
	print('    - Confirm on the peak pressure is 10 mbar and peep pressure is 1 mbar.')
	print('INTERACTIVE: Check that the flow graph.')
	print('    - Confirm on the peak pressure is 4 mbar and peep pressure is -4 mbar.')
	print('INTERACTIVE: Press the button to the left of the graph again to get back to the pressure graph.')
	print('    - Confirm on the peak pressure is 20 mbar and peep pressure is 5 mbar.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 80 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the PIP upper alarm limit below the actual PIP setting.')
	utility.promptForContinue()
	print('------------- step 81 ---------------')
	print('INTERACTIVE: Check that the High PIP/ High Pressure alarm is triggered. (This may take a few seconds)')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 82 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the PIP upper limit to 50 mbar and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 83 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the PIP lower alarm limit above the actual PIP setting.')
	utility.promptForContinue()
	print('------------- step 84 ---------------')
	print('INTERACTIVE: Check that the lower PIP alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 85 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the PIP low limit to off and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 86 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the Freq below the actual breath rate setting.')
	utility.promptForContinue()
	print('------------- step 87 ---------------')
	print('INTERACTIVE: Check that the High Breath rate alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 88 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the Freq to 100 and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 89 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the PEEP lower alarm limit above the actual PEEP setting.')
	utility.promptForContinue()
	print('------------- step 90 ---------------')
	print('INTERACTIVE: Check that the Low PEEP alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 91 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the Low PEEP alarm limit to 0.0 and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 92 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the MVexp upper alarm limit below the actual measured value.')
    utility.promptForContinue()
	print('------------- step 93 ---------------')
	print('INTERACTIVE: Check that the High minute volume alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 94 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the MVexp alarm upper limit to 5.0 and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 95 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the MVexp lower alarm limit higher the actual measured value.')
    utility.promptForContinue()
	print('------------- step 96 ---------------')
	print('INTERACTIVE: Check that the Low minute volume alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 97 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the MVexp alarm lower limit to off and wait for the alarm to clear.')
	utility.promptForContinue()
	print('------------- step 98 ---------------')
	print('INTERACTIVE: Press the button labeled "settings" and select "Volume Guarantee".')
	utility.promptForContinue()
	ft.setStateVGuarantee(1)
	print('INTERACTIVE: Set PMAX to 40.')
	utility.promptForContinue()
	ft.setVGuarantee__ml(10)
	print('------------- step 99 ---------------')
    ft.delay_sec(30)
	print('------------- step 100 --------------')
	verify.EXPECT_EQ(ft.getBTB().expMandTidalVolume, 10, pubFTI.volumeTolerance__ml) 
	print('------------- step 101 --------------')
	print('INTERACTIVE: Set PMAX to 10.')
	utility.promptForContinue()
	print('------------- step 102 ---------------')
    ft.delay_sec(30)
	print('------------- step 103 ---------------')
	print('INTERACTIVE: Check that the VTe not reached / check settings alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	ft.setStateVGuarantee(0)
	print('------------- step 104 ---------------')
	print('INTERACTIVE: Press the button labeled "settings" and select "Volume Limit".')
	utility.promptForContinue()
	ft.setStateVLimit(1)
	ft.setVLimit__ml(15)
	print('------------- step 105 ---------------')
    ft.delay_sec(30)
	print('------------- step 106 ---------------')
	print('INTERACTIVE: Check that there is no alarm.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 107 ---------------')
	ft.setVLimit__ml(1)
	print('------------- step 108 ---------------')
    ft.delay_sec(30)
	print('------------- step 109 ---------------')
	print('INTERACTIVE: Check that the Tidal Volume limited alarm is triggered.')
	print('    - If "Low minute volume" alarm active, select MVexp low alarm limit to "Autoset".')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 110 ---------------')
	ft.setStateVLimit(0)
	print('------------- step 111 ---------------')
	ft.setStatePressureRiseControl(1)
	ft.setRiseTime__sec(1)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20)
	ft.setBPM__bpm(30)
	ft.setITime__sec(1)
	ft.setO2(21)
	print('------------- step 112 ---------------')
    ft.delay_sec(30)
	print('------------- step 113 ---------------')
	print('INTERACTIVE: Check that the inspiratory pressure is increased lineraly to the Pinsp level during 1 second.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 114 ---------------')
    ft.setRiseTime__sec(0.1)
	print('------------- step 115 ---------------')
    ft.delay_sec(30)
	print('------------- step 116 ---------------')
	print('INTERACTIVE: Check that the Pressure reaches 20 mbar in 0.1 s and stays at 20 mbar for 0.9 s before the pressure drops.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 117 ---------------')
	ft.setStatePressureRiseControl(0)
	ft.setIFlow__lpm(1)
	ft.setPInsPressure__mbar(40)
	print('------------- step 118 ---------------')
    ft.delay_sec(30)
	print('------------- step 119 ---------------')
	print('INTERACTIVE: Check that the device cannot reach the set Pinsp of 40 mbar.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 120 ---------------')
	ft.setIFlow__lpm(10)
	print('------------- step 121 ---------------')
    ft.delay_sec(30)
	print('------------- step 122 ---------------')
	print('INTERACTIVE: Check that the device can reach the Pinsp level of 40 mbar.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	
	
	
    print("CMV test PASSED")
end

local function testASSIST()
    print('Test Assist mode:')
    print('------------- step 37 ---------------')
	ft.setVentMode(pubFTI.ventMode.SIPPV)
    ft.setIFlow__lpm(10)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20)
	ft.setETime__sec(8)
	ft.setBPM__bpm(30)
	ft.setITime__sec(1)
	ft.setTrigger(3)
	ft.setO2(21)
	print('------------- step 38 ---------------')
    ft.delay_sec(30)
	print('------------- step 39 ---------------')
	print('INTERACTIVE: Confirm that the graph shows a periodic breathing cycle.')
	print('INTERACTIVE: Confirm that the artifical lung is inflating and deflating.')
	verify.EXPECT_EQ(ft.getBTB().peakPressure, 20, pubFTI.pressureTolerance__cmH2O) 
	verify.EXPECT_EQ(ft.getBTB().PEEP, 5, pubFTI.pressureTolerance__cmH2O)
    verify.EXPECT_EQ(ft.getBTBAVG().respiratoryRate, 30, pubFTI.rateTolerance__bpm)	
	print('INTERACTIVE: No active alarms should occur during this time.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 40 ---------------')
    print('INTERACTIVE: Simulate spontaneous breaths.')
	utility.promptForContinue()
	print('------------- step 41 ---------------')
    print('INTERACTIVE: Check on the pressure graph that the simulated breaths are supported by the machine.')
	print('    - The graph pattern seen two steps ago should now be augmented with green to show the breaths caused by you squeezing the test lung.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 42 ---------------')
    print('INTERACTIVE: Stop simulating spontaneous breaths.')
	print("Assist test PASSED") 
end

local function testSIMV()
    print('Test SIMV mode:')
	print('------------- step 43 ---------------')
	ft.setVentMode(pubFTI.ventMode.SIMV)
	ft.setIFlow__lpm(10)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20)
	ft.setETime__sec(8)
	ft.setBPM__bpm(30)
	ft.setITime__sec(1)
	ft.setTrigger(1)
	ft.setO2(21)
	print('------------- step 44 ---------------')
    ft.delay_sec(30)
	print('------------- step 45 ---------------')
	print('INTERACTIVE: Confirm that the graph shows a periodic breathing cycle.')
	print('INTERACTIVE: Confirm that the artifical lung is inflating and deflating.')
	verify.EXPECT_EQ(ft.getBTB().peakPressure, 20, pubFTI.pressureTolerance__cmH2O) 
	verify.EXPECT_EQ(ft.getBTB().PEEP, 5, pubFTI.pressureTolerance__cmH2O)
    verify.EXPECT_EQ(ft.getBTBAVG().respiratoryRate, 30, pubFTI.pressureTolerance__cmH2O)	
	print('INTERACTIVE: No active alarms should occur during this time.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 46 ---------------')
    print('INTERACTIVE: Simulate spontaneous breaths.')
	utility.promptForContinue()
	print('------------- step 47 ---------------')
    print('INTERACTIVE: Check on the pressure graph that the simulated breaths are supported by the machine.')
	print('    - The graph pattern seen two steps ago should now be augmented with green to show the breaths caused by you squeezing the test lung.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
    print("SIMV test PASSED")
end

local function testSIMVPSV()
    print('Test SIMV+PSV mode:')
	print('------------- step 48 ---------------')
	ft.setVentMode(pubFTI.ventMode.SIMVPSV)
	ft.setIFlow__lpm(10)
	ft.setETime__sec(8)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20)
	ft.setPSV__mbar(10)
	ft.setBPM__bpm(10)
	ft.setITime__sec(1)
	ft.setTrigger(3)
	ft.setO2(21)
	print('------------- step 49 ---------------')
    ft.delay_sec(30)
	print('------------- step 50 ---------------')
	print('INTERACTIVE: Check that the ventilation occurs with the set parameters.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('INTERACTIVE: Select MVexp low alarm limit to "Autoset".')
	utility.promptForContinue()
	print('------------- step 51 ---------------')
	print('INTERACTIVE: Check that no patient alarms are activated.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 52 ---------------')
	print('INTERACTIVE: Simulate spontaneous breaths.')
	utility.promptForContinue()
	print('------------- step 53 ---------------')
	print('INTERACTIVE: Check on the pressure graph to see the PSV is 10 mbar and the simulated breaths are supported by the machine.')
    pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 75 ---------------')
	print('INTERACTIVE: Press the alarm limits physical button and enable Apnea alarm.')
	print('    -  Set the limit to 2 Sec.')
	utility.promptForContinue()
	print('------------- step 76 ---------------')
	print('INTERACTIVE: Check that the Apnea alarm is triggered.')
	pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 77 ---------------')
	print('INTERACTIVE: Press the alarm limits button and set the Apnea alarm to off and wait for the alarm to clear.')
	utility.promptForContinue()
	print("SIMV+PSV test PASSED")
end

local function testPSV()
    print('Test PSV mode:')
	print('------------- step 54 ---------------')
	ft.setVentMode(pubFTI.ventMode.PSV)
	ft.setIFlow__lpm(10)
	ft.setETime__sec(8)
	ft.setPeep__mbar(5)
	ft.setPInsPressure__mbar(20) --pbackup
	ft.setPSV__mbar(10)
	ft.setBackup(10)
	ft.setITime__sec(1)
	ft.setTrigger(3)
	ft.setO2(21)
	print('------------- step 55 ---------------')
    ft.delay_sec(30)
	print('INTERACTIVE: Select MVexp low alarm limit to "Autoset".')
	utility.promptForContinue()
	print('------------- step 56 ---------------')
    print('INTERACTIVE: Check that the apnea ventilation occurs with the set parameters.')
	local pass = utility.promptYesNoInput()
	utility.checkToContinue(pass)
	print('------------- step 57 ---------------')
	print('INTERACTIVE: Simulate spontaneous breaths.')
	utility.promptForContinue()
	print('------------- step 58 ---------------')
	print('INTERACTIVE: Check on the pressure graph to see the PSV is 10 mbar and the simulated breaths are supported by the machine.')
	pass = utility.utility.promptYesNoInput()
	utility.checkToContinue(pass)
    print("PSV test PASSED")
end


---------------------------------------------------------------------
-- function call
---------------------------------------------------------------------
ft.openCOM(portName)
ft.initalizeVent()
testCPAP()
testCMV() 
testASSIST()
testSIMV()
testSIMVPSV()
testPSV()
print('Please go to step 123 to finish the remainder of the regression test.')

ft.closeCOM()