------------------------------------------------------------------------------
-- (c) Copyright 2019 Vyaire Medical, or one of its subsidiaries.
--     All Rights Reserved.
------------------------------------------------------------------------------
-- Tests fabian Terminal Interface defined in FTI-define
------------------------------------------------------------------------------

local fti = require "FTI-Define"
local verify = require "verify"

local function EXPECT_EQ(xValue, xExpected, xMsg)
    assert(xValue == xExpected, 'ASSERT: ' .. xMsg .. '. Value is ' .. tonumber(xValue) .. ', expected ' .. tonumber(xExpected))
end

function test_VentModeRange()
    local minMode = 1
    local maxMode = 10
    
    local isValidMode = (minMode >= FTI.ventMode.IPPV) and (maxMode <= FTI.ventMode.O2Therapy)
    verify.EXPECT_TRUE(isValidMode, 'Vent Mode Check ')

    local expectedServiceMode = 15  
    local isServiceMode = FTI.ventMode.SERVICE == expectedServiceMode
    verify.EXPECT_TRUE(isServiceMode, 'Service Mode Check ')
end

function test_VentModes()
    test_VentModeRange()

    local mode = FTI.ventMode  -- expected Value
    verify.EXPECT_EQ(mode.NONE     ,    0,      'Vent Mode NONE     ')
    verify.EXPECT_EQ(mode.IPPV     ,    1,      'Vent Mode IPPV     ')
    verify.EXPECT_EQ(mode.SIPPV    ,    2,      'Vent Mode SIPPV    ')
    verify.EXPECT_EQ(mode.SIMV     ,    3,      'Vent Mode SIMV     ')
    verify.EXPECT_EQ(mode.SIMVPSV  ,    4,      'Vent Mode SIMVPSV  ')
    verify.EXPECT_EQ(mode.PSV      ,    5,      'Vent Mode PSV      ')
    verify.EXPECT_EQ(mode.CPAP     ,    6,      'Vent Mode CPAP     ')
    verify.EXPECT_EQ(mode.NCPAP    ,    7,      'Vent Mode NCPAP    ')
    verify.EXPECT_EQ(mode.DUOPAP   ,    8,      'Vent Mode DUOPAP   ')
    verify.EXPECT_EQ(mode.HFO      ,    9,      'Vent Mode HFO      ')
    verify.EXPECT_EQ(mode.O2Therapy,   10,      'Vent Mode O2Therapy')
    verify.EXPECT_EQ(mode.SERVICE  ,   15,      'Vent Mode SERVICE  ')
end

function test_ModeOption1()
    local modeOpt1 = FTI.ModeOption1                         -- expected Value
    verify.EXPECT_EQ(modeOpt1.StartStopBit                        ,  0, 'ModeOption1 StartStopBit                         ')
    verify.EXPECT_EQ(modeOpt1.StateVolumnGuaranteeBit             ,  1, 'ModeOption1 StateVolumnGuaranteeBit              ')
    verify.EXPECT_EQ(modeOpt1.StateVolumnLimitBit                 ,  2, 'ModeOption1 StateVolumnLimitBit                  ')
    verify.EXPECT_EQ(modeOpt1.VentilatorRangeBit                  ,  3, 'ModeOption1 VentilatorRangeBit                   ')
    verify.EXPECT_EQ(modeOpt1.FlowSensorCalibrationRunningBit     ,  4, 'ModeOption1 FlowSensorCalibrationRunningBit      ')
    verify.EXPECT_EQ(modeOpt1.O2CompensationEnabledBit            ,  5, 'ModeOption1 O2CompensationEnabledBit             ')
    verify.EXPECT_EQ(modeOpt1.ExhalationValveCalibrationRunningBit,  6, 'ModeOption1 ExhalationValveCalibrationRunningBit ')
    verify.EXPECT_EQ(modeOpt1.TriggerModeBit                      ,  7, 'ModeOption1 TriggerModeBit                       ')
    verify.EXPECT_EQ(modeOpt1.CalibrationProcess_21_O2_RunningBit ,  8, 'ModeOption1 CalibrationProcess_21_O2_RunningBit  ')
    verify.EXPECT_EQ(modeOpt1.CalibrationProcess_100_O2_RunningBit,  9, 'ModeOption1 CalibrationProcess_100_O2_RunningBit ')
    verify.EXPECT_EQ(modeOpt1.TubeSet_InfantFlow_MediJetBit       , 10, 'ModeOption1 TubeSet_InfantFlow_MediJetBit        ')
    verify.EXPECT_EQ(modeOpt1.TubeSet_InfantFlowLPBit             , 11, 'ModeOption1 TubeSet_InfantFlowLPBit              ')
    verify.EXPECT_EQ(modeOpt1.IERatioHFOBit11                     , 12, 'ModeOption1 IERatioHFOBit11                      ')
    verify.EXPECT_EQ(modeOpt1.IERatioHFOBit12                     , 13, 'ModeOption1 IERatioHFOBit12                      ')
    verify.EXPECT_EQ(modeOpt1.InternalUseBit                      , 14, 'ModeOption1 InternalUseBit                       ')
    verify.EXPECT_EQ(modeOpt1.ManualBreathRunningBit              , 15, 'ModeOption1 ManualBreathRunningBit               ')
end

function test_ModeOption2()
    local modeOpt2 = FTI.ModeOption2            -- expected Value
    verify.EXPECT_EQ(modeOpt2.PressureRiseControlBit0 ,  0, 'ModeOption2 PressureRiseControlBit0  ')
    verify.EXPECT_EQ(modeOpt2.PressureRiseControlBit1 ,  1, 'ModeOption2 PressureRiseControlBit1  ')
    verify.EXPECT_EQ(modeOpt2.HFORecruitmentBit       ,  2, 'ModeOption2 HFORecruitmentBit        ')
    verify.EXPECT_EQ(modeOpt2.HFOFlowBit              ,  3, 'ModeOption2 HFOFlowBit               ')
    verify.EXPECT_EQ(modeOpt2.ReservedBit             ,  4, 'ModeOption2 ReservedBit              ')
    verify.EXPECT_EQ(modeOpt2.BiasFlowBit             ,  5, 'ModeOption2 BiasFlowBit              ')
    verify.EXPECT_EQ(modeOpt2.TriggerModeBit6         ,  6, 'ModeOption2 TriggerModeBit6          ')
    verify.EXPECT_EQ(modeOpt2.TriggerModeBit7         ,  7, 'ModeOption2 TriggerModeBit7          ')
    verify.EXPECT_EQ(modeOpt2.TriggerModeBit8         ,  8, 'ModeOption2 TriggerModeBit8          ')
    verify.EXPECT_EQ(modeOpt2.FOTOscillationRunningBit,  9, 'ModeOption2 FOTOscillationRunningBit ')
    verify.EXPECT_EQ(modeOpt2.LeakCompensationBit10   , 10, 'ModeOption2 LeakCompensationBit10    ')
    verify.EXPECT_EQ(modeOpt2.LeakCompensationBit11   , 11, 'ModeOption2 LeakCompensationBit11    ')
end

function test_para_get_VentSettings()
    local vs = FTI.para_get_VentSettings                -- expected Value
    verify.EXPECT_EQ(vs.TERMINAL_GET_VENT_RUNSTATE          ,  0x09, 'TERMINAL_GET_VENT_RUNSTATE          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_STATE_VLimit           ,  0x0A, 'TERMINAL_GET_STATE_VLimit           ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_STATE_VGarant          ,  0x0B, 'TERMINAL_GET_STATE_VGarant          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_VentRange        ,  0x0C, 'TERMINAL_GET_PARAM_VentRange        ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_IERatioHFO       ,  0x0D, 'TERMINAL_GET_PARAM_IERatioHFO       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_MANBREATHrunning       ,  0x0E, 'TERMINAL_GET_MANBREATHrunning       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PressureRiseCtrl       ,  0x0F, 'TERMINAL_GET_PressureRiseCtrl       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFOFreqRec       ,  0x10, 'TERMINAL_GET_PARAM_HFOFreqRec       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFOFlow          ,  0x11, 'TERMINAL_GET_PARAM_HFOFlow          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_LeakCompensation       ,  0x12, 'TERMINAL_GET_LeakCompensation       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_TriggerOption          ,  0x13, 'TERMINAL_GET_TriggerOption          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_FOToscillationState    ,  0x14, 'TERMINAL_GET_FOToscillationState    ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_PINSP            ,  0x15, 'TERMINAL_GET_PARAM_PINSP            ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_PEEP             ,  0x16, 'TERMINAL_GET_PARAM_PEEP             ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_PPSV             ,  0x17, 'TERMINAL_GET_PARAM_PPSV             ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_BPM              ,  0x18, 'TERMINAL_GET_PARAM_BPM              ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFAmpl           ,  0x19, 'TERMINAL_GET_PARAM_HFAmpl           ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFAmplMax        ,  0x1A, 'TERMINAL_GET_PARAM_HFAmplMax        ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFFreq           ,  0x1B, 'TERMINAL_GET_PARAM_HFFreq           ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_O2               ,  0x1C, 'TERMINAL_GET_PARAM_O2               ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_IFlow            ,  0x1D, 'TERMINAL_GET_PARAM_IFlow            ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_EFlow            ,  0x1E, 'TERMINAL_GET_PARAM_EFlow            ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_Risetime         ,  0x1F, 'TERMINAL_GET_PARAM_Risetime         ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_ITime            ,  0x20, 'TERMINAL_GET_PARAM_ITime            ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_ETime            ,  0x21, 'TERMINAL_GET_PARAM_ETime            ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFPMean          ,  0x22, 'TERMINAL_GET_PARAM_HFPMean          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_HFPMeanRec       ,  0x23, 'TERMINAL_GET_PARAM_HFPMeanRec       ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_VLimit           ,  0x24, 'TERMINAL_GET_PARAM_VLimit           ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_VGarant          ,  0x25, 'TERMINAL_GET_PARAM_VGarant          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_AbortCriterionPSV,  0x26, 'TERMINAL_GET_PARAM_AbortCriterionPSV')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_TherapieFlow     ,  0x27, 'TERMINAL_GET_PARAM_TherapieFlow     ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_Trigger          ,  0x28, 'TERMINAL_GET_PARAM_Trigger          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_Flowmin          ,  0x29, 'TERMINAL_GET_PARAM_Flowmin          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_CPAP             ,  0x2A, 'TERMINAL_GET_PARAM_CPAP             ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_PManual          ,  0x2B, 'TERMINAL_GET_PARAM_PManual          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_Backup           ,  0x2C, 'TERMINAL_GET_PARAM_Backup           ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_ITimeRec         ,  0x2D, 'TERMINAL_GET_PARAM_ITimeRec         ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_ETIMERec         ,  0x2E, 'TERMINAL_GET_PARAM_ETIMERec         ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_SPO2LOW          ,  0x2F, 'TERMINAL_GET_PARAM_SPO2LOW          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_SPO2HIGH         ,  0x30, 'TERMINAL_GET_PARAM_SPO2HIGH         ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_FIO2LOW          ,  0x31, 'TERMINAL_GET_PARAM_FIO2LOW          ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_PARAM_FIO2HIGH         ,  0x32, 'TERMINAL_GET_PARAM_FIO2HIGH         ')
    verify.EXPECT_EQ(vs.TERMINAL_GET_STATE_PRICO            ,  0x33, 'TERMINAL_GET_STATE_PRICO            ')
end

function test_para_set_settingData()
    local sd = FTI.para_set_settingData                -- expected Value
    verify.EXPECT_EQ(sd.TERMINAL_SET_VENT_RUNSTATE          ,  0x55, 'TERMINAL_SET_VENT_RUNSTATE          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_STATE_VLimit           ,  0x56, 'TERMINAL_SET_STATE_VLimit           ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_STATE_VGarant          ,  0x57, 'TERMINAL_SET_STATE_VGarant          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_VentRange        ,  0x58, 'TERMINAL_SET_PARAM_VentRange        ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_IERatioHFO       ,  0x59, 'TERMINAL_SET_PARAM_IERatioHFO       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_MANBREATHrunning       ,  0x5A, 'TERMINAL_SET_MANBREATHrunning       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PressureRiseCtrl       ,  0x5B, 'TERMINAL_SET_PressureRiseCtrl       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFOFreqRec       ,  0x5C, 'TERMINAL_SET_PARAM_HFOFreqRec       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFOFlow          ,  0x5D, 'TERMINAL_SET_PARAM_HFOFlow          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_LeakCompensation       ,  0x5E, 'TERMINAL_SET_LeakCompensation       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_PINSP            ,  0x60, 'TERMINAL_SET_PARAM_PINSP            ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_PEEP             ,  0x61, 'TERMINAL_SET_PARAM_PEEP             ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_PPSV             ,  0x62, 'TERMINAL_SET_PARAM_PPSV             ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_BPM              ,  0x63, 'TERMINAL_SET_PARAM_BPM              ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFAmpl           ,  0x64, 'TERMINAL_SET_PARAM_HFAmpl           ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFAmplMax        ,  0x65, 'TERMINAL_SET_PARAM_HFAmplMax        ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFFreq           ,  0x66, 'TERMINAL_SET_PARAM_HFFreq           ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_O2               ,  0x67, 'TERMINAL_SET_PARAM_O2               ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_IFlow            ,  0x68, 'TERMINAL_SET_PARAM_IFlow            ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_EFlow            ,  0x6A, 'TERMINAL_SET_PARAM_EFlow            ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_RiseTime         ,  0x6B, 'TERMINAL_SET_PARAM_RiseTime         ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_ITime            ,  0x6C, 'TERMINAL_SET_PARAM_ITime            ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_ETime            ,  0x6D, 'TERMINAL_SET_PARAM_ETime            ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFPMean          ,  0x6E, 'TERMINAL_SET_PARAM_HFPMean          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_HFPMeanRec       ,  0x6F, 'TERMINAL_SET_PARAM_HFPMeanRec       ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_VLimit           ,  0x70, 'TERMINAL_SET_PARAM_VLimit           ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_VGarant          ,  0x71, 'TERMINAL_SET_PARAM_VGarant          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_AbortCriterionPSV,  0x72, 'TERMINAL_SET_PARAM_AbortCriterionPSV')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_TherapieFlow     ,  0x73, 'TERMINAL_SET_PARAM_TherapieFlow     ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_Trigger          ,  0x74, 'TERMINAL_SET_PARAM_Trigger          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_Flowmin          ,  0x75, 'TERMINAL_SET_PARAM_Flowmin          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_CPAP             ,  0x76, 'TERMINAL_SET_PARAM_CPAP             ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_PManual          ,  0x77, 'TERMINAL_SET_PARAM_PManual          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_Backup           ,  0x78, 'TERMINAL_SET_PARAM_Backup           ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_ITimeRec         ,  0x79, 'TERMINAL_SET_PARAM_ITimeRec         ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_O2_FLUSH         ,  0x7A, 'TERMINAL_SET_PARAM_O2_FLUSH         ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_SPO2LOW          ,  0x7B, 'TERMINAL_SET_PARAM_SPO2LOW          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_SPO2HIGH         ,  0x7C, 'TERMINAL_SET_PARAM_SPO2HIGH         ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_FIO2LOW          ,  0x7D, 'TERMINAL_SET_PARAM_FIO2LOW          ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_PARAM_FIO2HIGH         ,  0x7E, 'TERMINAL_SET_PARAM_FIO2HIGH         ')
    verify.EXPECT_EQ(sd.TERMINAL_SET_STATE_PRICO            ,  0x7F, 'TERMINAL_SET_STATE_PRICO            ')
end

function test_para_measure_response()
    local mr = FTI.para_measure_response   -- expected Value
    verify.EXPECT_EQ(mr.None             ,   0, 'None             ')
    verify.EXPECT_EQ(mr.ActiveVentMode   ,   4, 'ActiveVentMode   ')
    verify.EXPECT_EQ(mr.Pmax             ,   5, 'Pmax             ')
    verify.EXPECT_EQ(mr.Pmitt            ,   7, 'Pmitt            ')
    verify.EXPECT_EQ(mr.PEEP             ,   9, 'PEEP             ')
    verify.EXPECT_EQ(mr.DynamicCompliance,  11, 'DynamicCompliance')
    verify.EXPECT_EQ(mr.C20C             ,  13, 'C20C             ')
    verify.EXPECT_EQ(mr.Resistance       ,  15, 'Resistance       ')
    verify.EXPECT_EQ(mr.MV               ,  17, 'MV               ')
    verify.EXPECT_EQ(mr.TVI              ,  19, 'TVI              ')
    verify.EXPECT_EQ(mr.TVE              ,  21, 'TVE              ')
    verify.EXPECT_EQ(mr.TVEresp          ,  23, 'TVEresp          ')
    verify.EXPECT_EQ(mr.TVEpat           ,  25, 'TVEpat           ')
    verify.EXPECT_EQ(mr.HFAmpl           ,  27, 'HFAmpl           ')
    verify.EXPECT_EQ(mr.TVEHFO           ,  29, 'TVEHFO           ')
    verify.EXPECT_EQ(mr.DCO2             ,  31, 'DCO2             ')
    verify.EXPECT_EQ(mr.TrigVol          ,  33, 'TrigVol          ')
    verify.EXPECT_EQ(mr.ITimePSV         ,  35, 'ITimePSV         ')
    verify.EXPECT_EQ(mr.SPO2             ,  37, 'SPO2             ')
    verify.EXPECT_EQ(mr.PulseRate        ,  39, 'PulseRate        ')
    verify.EXPECT_EQ(mr.PerfusionIndex   ,  41, 'PerfusionIndex   ')
    verify.EXPECT_EQ(mr.ETCO2            ,  43, 'ETCO2            ')
    verify.EXPECT_EQ(mr.BPM              ,  45, 'BPM              ')
    verify.EXPECT_EQ(mr.BPMco2           ,  47, 'BPMco2           ')
    verify.EXPECT_EQ(mr.Leak             ,  49, 'Leak             ')
    verify.EXPECT_EQ(mr.HFFreq           ,  51, 'HFFreq           ')
    verify.EXPECT_EQ(mr.Percent          ,  53, 'Percent          ')
    verify.EXPECT_EQ(mr.OxyVal           ,  55, 'OxyVal           ')
    verify.EXPECT_EQ(mr.INSP_FLOW        ,  57, 'INSP_FLOW        ')
    verify.EXPECT_EQ(mr.EXP_FLOW         ,  59, 'EXP_FLOW         ')
    verify.EXPECT_EQ(mr.DEMAND_FLOW      ,  61, 'DEMAND_FLOW      ')
end

function test_para_get_waveData()
    local wd = FTI.para_get_waveData
    verify.EXPECT_EQ(wd.Pressure,  3, 'Pressure')
    verify.EXPECT_EQ(wd.Flow    ,  5, 'Flow    ')
    verify.EXPECT_EQ(wd.etCO2   ,  7, 'etCO2   ')
end

function test_command()
    local cmd = FTI.command                             -- expected Value
    verify.EXPECT_EQ(cmd.TERM_STOP_CONTINUOUS_MEASUREMENTS    ,  0x50,     'TERM_STOP_CONTINUOUS_MEASUREMENTS    ')
    verify.EXPECT_EQ(cmd.TERM_STOP_WAVE_DATA                  ,  0x51,     'TERM_STOP_WAVE_DATA                  ')
    verify.EXPECT_EQ(cmd.TERM_MSG_SOM                         ,  0x02,     'TERM_MSG_SOM                         ')
    verify.EXPECT_EQ(cmd.TERM_PARAM_NOSUPPORT                 ,  0xFD,     'TERM_PARAM_NOSUPPORT                 ')
    verify.EXPECT_EQ(cmd.TERM_PARAM_OUTOFFRANGE               ,  0xFF,     'TERM_PARAM_OUTOFFRANGE               ')
    verify.EXPECT_EQ(cmd.TERM_GET_MEASUREMENTS_ONCE_BTB       ,  0x00,     'TERM_GET_MEASUREMENTS_ONCE_BTB       ')
    verify.EXPECT_EQ(cmd.TERM_GET_MEASUREMENTS_CONTINIOUS_BTB ,  0x01,     'TERM_GET_MEASUREMENTS_CONTINIOUS_BTB ')
    verify.EXPECT_EQ(cmd.TERM_GET_MEASUREMENTS_ONCE_AVG       ,  0x02,     'TERM_GET_MEASUREMENTS_ONCE_AVG       ')
    verify.EXPECT_EQ(cmd.TERM_GET_MEASUREMENTS_CONTINIOUS_AVG ,  0x03,     'TERM_GET_MEASUREMENTS_CONTINIOUS_AVG ')
    verify.EXPECT_EQ(cmd.TERM_MEASUREMENTS_BTB                ,  0x00,     'TERM_MEASUREMENTS_BTB                ')
    verify.EXPECT_EQ(cmd.TERM_MEASUREMENTS_AVG                ,  0x02,     'TERM_MEASUREMENTS_AVG                ')
    verify.EXPECT_EQ(cmd.TERM_GET_WAVE_DATA                   ,  0x04,     'TERM_GET_WAVE_DATA                   ')
    verify.EXPECT_EQ(cmd.TERM_GET_VENT_MODE                   ,  0x05,     'TERM_GET_VENT_MODE                   ')
    verify.EXPECT_EQ(cmd.TERM_GET_MODE_OPTION1                ,  0x06,     'TERM_GET_MODE_OPTION1                ')
    verify.EXPECT_EQ(cmd.TERM_GET_MODE_OPTION2                ,  0x07,     'TERM_GET_MODE_OPTION2                ')
    verify.EXPECT_EQ(cmd.TERM_STOP_CONTINUOUS_MEASUREMENTS    ,  0x50,     'TERM_STOP_CONTINUOUS_MEASUREMENTS    ')
    verify.EXPECT_EQ(cmd.TERM_STOP_WAVE_DATA                  ,  0x51,     'TERM_STOP_WAVE_DATA                  ')
    verify.EXPECT_EQ(cmd.TERM_MEASUREMENTS_BTB                ,  0x00,     'TERM_MEASUREMENTS_BTB                ')
    verify.EXPECT_EQ(cmd.TERM_MEASUREMENTS_AVG                ,  0x02,     'TERM_MEASUREMENTS_AVG                ')
    verify.EXPECT_EQ(cmd.TERM_WAVE_DATA                       ,  0x04,     'TERM_WAVE_DATA                       ')
    verify.EXPECT_EQ(cmd.TERM_VENT_MODE                       ,  0x05,     'TERM_VENT_MODE                       ')
    verify.EXPECT_EQ(cmd.TERM_MODE_OPTION1                    ,  0x06,     'TERM_MODE_OPTION1                    ')
    verify.EXPECT_EQ(cmd.TERM_MODE_OPTION2                    ,  0x07,     'TERM_MODE_OPTION2                    ')
end

----------------------------------------------------------------------------------------
-- Call function tests
----------------------------------------------------------------------------------------
test_VentModeRange()
test_VentModes()
test_ModeOption1()
test_ModeOption2()
test_para_get_VentSettings()
test_para_set_settingData()
test_para_measure_response()
test_para_get_waveData()
test_command()
